# This is a multi-project pipeline
# it will trigger downstream pipelines
# using hints from template
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml

workflow:
  rules:
  - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH == "master") || $CI_COMMIT_BRANCH == "master"
    changes:
      - ./**/*.tf
      - ./**/*.sh
    when: always
  - when: never

variables:
  TF_STATE: ${CI_PROJECT_NAME}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}

include:
#  - template: Terraform/Base.gitlab-ci.yml
  - local: 'Base.gitlab-ci.yml'

stages:
  - validate_infrastructure_code
  - build_infrastructure_plan
  - deploy_infrastructure

validate:
  stage: validate_infrastructure_code
  extends:
    .terraform:validate

plan:
  stage: build_infrastructure_plan
  extends:
    .terraform:build # ==plan
  before_script:
    - cat "$TF_VARS" > "$(pwd)/terraform.tfvars"
    - mkdir "$(pwd)/.oci"
    - cat "$KEY_FILE" > "$(pwd)/.oci/terraform-configuration_2022-06-11T13 01 59.878Z.pem"
    - cat "$WS_KEY_PUB" > "$(pwd)/.oci/wskey.pub"
    - export TF_ADDRESS=$TF_ADDRESS
    - echo $TF_ADDRESS
    - |
      terraform init -reconfigure \
      -backend-config="address=${TF_ADDRESS}" \
      -backend-config="lock_address=${TF_ADDRESS}/lock" \
      -backend-config="unlock_address=${TF_ADDRESS}/lock" \
      -backend-config="username=gitlab-ci-token" \
      -backend-config="password=${CI_JOB_TOKEN}" \
      -backend-config="lock_method=POST" \
      -backend-config="unlock_method=DELETE" \
      -backend-config="retry_wait_min=5"


apply:
  stage: deploy_infrastructure
  extends: .terraform:deploy # ==apply
  dependencies:
    - plan
  before_script:
    - cat "$TF_VARS" > "$(pwd)/terraform.tfvars"
    - mkdir "$(pwd)/.oci"
    - cat "$KEY_FILE" > "$(pwd)/.oci/terraform-configuration_2022-06-11T13 01 59.878Z.pem"
    - cat "$WS_KEY_PUB" > "$(pwd)/.oci/wskey.pub"
    - ls -htla
  environment:
    name: $TF_STATE
  when: manual









