# This is a multi-project pipeline
# it will trigger downstream pipelines

workflow:
  rules:
    - when: always

variables:
  TF_STATE: ${CI_PROJECT_NAME}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}

include:
#  - template: Terraform/Base.gitlab-ci.yml
  - local: 'Base.gitlab-ci.yml'

stages:
  - build_infrastructure
  - deploy_infrastructure

validate_infrastructure:
  stage: build_infrastructure
  extends:
    .terraform:validate

plan_infrastructure:
  stage: build_infrastructure
  needs:
    - validate_infrastructure
  extends:
    .terraform:build
  before_script:
    - cat "$TF_VARS" > "$(pwd)/terraform.tfvars"
    - mkdir "$(pwd)/.oci"
    - cat "$KEY_FILE" > "$(pwd)/.oci/terraform-configuration_2022-06-11T13 01 59.878Z.pem"
    - cat "$WS_KEY_PUB" > "$(pwd)/.oci/wskey.pub"
    - export TF_ADDRESS=$TF_ADDRESS
    - echo $TF_ADDRESS








