# This is a multi-project pipeline
# it will trigger downstream pipelines

workflow:
  rules:
    - when: always


include:
#  - template: Terraform/Base.gitlab-ci.yml
  - local: 'Base.gitlab-ci.yml'

stages:
  - build_infrastructure
  - deploy_infrastructure

validate_infrastructure:
  stage: build_infrastructure
  extends:
    .terraform:validate

plan_infrastructure:
  stage: build_infrastructure
  needs:
    - validate_infrastructure
  extends:
    .terraform:build
  before_script:
    - cat "$TF_VARS" > "$(pwd)/terraform.tfvars"
    - echo $TF_VARS
    - ls







