# https://docs.gitlab.com/runner/register/index.html#runners-configuration-template-file
[[runners]]
  name = "oci-micro-instance-dind-runner"
  url = "https://gitlab.com/"
  token = ""
  executor = "docker"
  cache_dir = "/cache"
  [runners.custom_build_dir]
  [runners.cache]
    Type = "s3"
    Shared = true
    [runners.cache.s3]
      ServerAddress = ""
      AccessKey = ""
      SecretKey = ""
      BucketName = ""
      BucketLocation = ""
      Insecure = false
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:20.10.17"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs/client", "/cache"]
    shm_size = 0